# Generated by Django 5.2.7 on 2026-05-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_details_job_type_product_material_heat_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='customer_dc_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='job_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
