# Generated by Django 5.2.7 on 2026-05-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_details_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_Remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='customer_dc_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='job_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
