# Generated by Django 5.2.7 on 2026-05-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quotation_client_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='client_Remarks',
            new_name='client_remarks',
        ),
    ]
