# Generated by Django 5.2.7 on 2026-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_client_remarks_quotation_client_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='monthly_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='monthly_maintenance_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='weekly_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='weekly_maintenance_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
