# Generated by Django 5.2.7 on 2026-07-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_machine_monthly_maintenance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=20)),
                ('scheduled_date', models.DateField()),
                ('approved_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='api.machine')),
            ],
        ),
    ]
