# Generated by Django 5.2.7 on 2026-07-06 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_machinemaintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=120)),
                ('requested_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requested_by', models.CharField(blank=True, max_length=120)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='parts_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InventoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=120)),
                ('part_type', models.CharField(default='Spare Part', max_length=60)),
                ('machine_type', models.CharField(choices=[('common', 'Common Machine Part'), ('new', 'New Machine Part')], default='common', max_length=20)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('bought_from', models.CharField(blank=True, max_length=120)),
                ('bought_by', models.CharField(blank=True, max_length=120)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('warranty', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='in_stock', max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_parts', to='api.machine')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('machine_name', models.CharField(blank=True, max_length=120)),
                ('user', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='api.inventorypart')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, max_length=120)),
                ('used_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_by', models.CharField(blank=True, max_length=120)),
                ('used_hours', models.CharField(blank=True, max_length=40)),
                ('used_date', models.DateField(default=django.utils.timezone.now)),
                ('maintenance_type', models.CharField(blank=True, max_length=30)),
                ('remaining_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_usage', to='api.machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='api.inventorypart')),
            ],
        ),
    ]
