# Generated by Django 5.2.7 on 2026-07-07 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pendingmaterial_machinemaintenancelog_parts_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemaintenancelog',
            name='approved_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
