# Generated by Django 5.2.7 on 2026-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_approved_date_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='monthly_maintenance_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='weekly_maintenance_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
