# Generated by Django 5.2.7 on 2026-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_machine_monthly_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='monthly_maintenance_interval',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='weekly_maintenance_interval',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
