# Generated by Django 5.2.7 on 2026-07-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_machine_monthly_maintenance_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='monthly_last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='monthly_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='monthly_maintenance_interval',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='monthly_maintenance_needs',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='monthly_maintenance_status',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='weekly_last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='weekly_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='weekly_maintenance_interval',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='weekly_maintenance_needs',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='weekly_maintenance_status',
        ),
        migrations.RemoveField(
            model_name='machinemaintenancelog',
            name='maintenance_type',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='maintenance_type',
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='maintenance_name',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.maintenanceschedule'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='interval_days',
            field=models.IntegerField(default=30, help_text='Maintenance cycle in days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='maintenance_name',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='next_maintenance_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
