# Generated by Django 5.2.7 on 2026-07-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_machine_monthly_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypart',
            name='part_type',
        ),
    ]
