# Generated by Django 5.2.7 on 2026-07-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_inventorypart_part_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypart',
            name='machine_type',
        ),
    ]
