# Generated by Django 5.2.7 on 2026-08-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_inventoryusagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypart',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventorypart',
            name='spare_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
