# Generated by Django 5.2.7 on 2026-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_inventorypart_item_code_inventorypart_spare_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypart',
            name='min_stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
