# Generated by Django 5.2.7 on 2026-08-04 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_inventorypart_min_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(blank=True, max_length=50, null=True)),
                ('breakdown_date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('affected_equipment', models.CharField(blank=True, max_length=120, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('breakdown_time', models.TimeField(blank=True, null=True)),
                ('breakdown_type', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_start_time', models.TimeField(blank=True, null=True)),
                ('maintenance_complete_time', models.TimeField(blank=True, null=True)),
                ('restart_time', models.TimeField(blank=True, null=True)),
                ('breakdown_complete_date', models.DateField(blank=True, null=True)),
                ('total_downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_records', to='api.machine')),
            ],
        ),
    ]
