# Generated by Django 5.2.7 on 2026-08-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_breakdownmaintenance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryUsageType',
            new_name='InventoryPurpose',
        ),
    ]
