# Generated by Django 5.2.7 on 2026-08-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_inventorypart_new_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypart',
            name='new_available_quantity',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='new_purchase_date',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='new_stock_quantity',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='new_used_quantity',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='old_available_quantity',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='old_purchase_date',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='old_stock_quantity',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='old_used_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryusage',
            name='stock_bucket',
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='use_new_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
