# Generated by Django 5.2.7 on 2026-08-14 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_inventorypart_new_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryusage',
            name='used_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
