# Generated by Django 5.2.7 on 2026-08-18 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_inventoryusage_used_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('kpi_category', models.CharField(default='Production', max_length=100)),
                ('kpi_parameter', models.CharField(default='Machine Utilization', max_length=100)),
                ('formula', models.CharField(default='Planned Hours / Runtime (HH:MM) * 100', max_length=200)),
                ('target', models.CharField(blank=True, default='85-90%', max_length=50, null=True)),
                ('frequency', models.CharField(default='Monthly', max_length=50)),
                ('responsible', models.CharField(blank=True, default='Production', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('month', 'kpi_category', 'kpi_parameter')},
            },
        ),
    ]
