# Generated by Django 5.2.7 on 2026-08-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_kpirecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpirecord',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
