# Generated by Django 5.2.7 on 2026-08-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_kpirecord_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpirecord',
            name='achieved',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
