# Generated by Django 5.2.7 on 2026-08-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_kpirecord_achieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpirecord',
            name='achieved',
        ),
    ]
