# Generated by Django 5.2.7 on 2026-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_kpirecord_achieved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpirecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='s_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='kpirecord',
            unique_together={('month', 's_no')},
        ),
    ]
