# Generated by Django 5.2.7 on 2026-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_kpirecord_unique_together_kpirecord_s_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpirecord',
            name='achieved',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
