# Generated by Django 5.2.7 on 2026-08-20 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_kpirecord_achieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=1, unique=True)),
                ('kpi_category', models.CharField(default='Production', max_length=100)),
                ('kpi_parameter', models.CharField(default='Machine Utilization', max_length=100)),
                ('formula', models.CharField(default='Planned Hours / Runtime (HH:MM) * 100', max_length=200)),
                ('target', models.CharField(blank=True, default='85-90%', max_length=50, null=True)),
                ('frequency', models.CharField(default='Monthly', max_length=50)),
                ('responsible', models.CharField(blank=True, default='Production', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kpi_template',
                'ordering': ['s_no'],
            },
        ),
    ]
