# Generated by Django 5.2.7 on 2026-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_kpitemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpitemplate',
            options={'ordering': ['group_id', 's_no']},
        ),
        migrations.AlterUniqueTogether(
            name='kpirecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kpirecord',
            name='group_id',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='kpitemplate',
            name='group_id',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='kpitemplate',
            name='s_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='kpirecord',
            unique_together={('group_id', 'month', 's_no')},
        ),
        migrations.AlterUniqueTogether(
            name='kpitemplate',
            unique_together={('group_id', 's_no')},
        ),
    ]
