# Generated by Django 5.2.7 on 2026-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_kpitemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitemplate',
            name='achieved',
            field=models.CharField(blank=True, default='0.00%', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kpitemplate',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
