# Generated by Django 5.2.7 on 2026-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_kpitemplate_achieved_kpitemplate_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
