# Generated by Django 5.2.7 on 2026-08-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_kpitemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitemplate',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
