# Generated by Django 5.2.7 on 2026-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_kpitemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpirecord',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
