# Generated by Django 5.2.7 on 2026-08-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_kpirecord_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kpitemplate',
            name='achieved',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
