# Generated by Django 5.2.17 on 2026-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_all_user_password_alter_kpitemplate_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
