# Generated by Django 5.2.17 on 2026-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_maintenanceschedule_created_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['part_name'], name='api_invento_part_na_79033d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['action'], name='api_invento_action_6c9b49_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['-created_at'], name='api_invento_created_80c330_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['part'], name='api_invento_part_id_b028ee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypart',
            index=models.Index(fields=['part_name'], name='api_invento_part_na_8fc47b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypart',
            index=models.Index(fields=['status'], name='api_invento_status_88ee70_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypart',
            index=models.Index(fields=['machine'], name='api_invento_machine_ba48cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypart',
            index=models.Index(fields=['-created_at'], name='api_invento_created_cb3334_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryratehistory',
            index=models.Index(fields=['part', '-created_at'], name='api_invento_part_id_9d7e93_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['part'], name='api_invento_part_id_4705ba_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['machine'], name='api_invento_machine_16df60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['-used_date'], name='api_invento_used_da_0a9121_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingmaterial',
            index=models.Index(fields=['status'], name='api_pending_status_f3ccb9_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingmaterial',
            index=models.Index(fields=['priority'], name='api_pending_priorit_821b07_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingmaterial',
            index=models.Index(fields=['-request_date'], name='api_pending_request_179b01_idx'),
        ),
    ]
