# Generated by Django 5.2.17 on 2026-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_inventoryhistory_api_invento_part_na_79033d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acc_details',
            index=models.Index(fields=['material'], name='api_acc_det_materia_06683f_idx'),
        ),
        migrations.AddIndex(
            model_name='acc_details',
            index=models.Index(fields=['invoice_no'], name='api_acc_det_invoice_150a22_idx'),
        ),
        migrations.AddIndex(
            model_name='acc_details',
            index=models.Index(fields=['status'], name='api_acc_det_status_d25834_idx'),
        ),
        migrations.AddIndex(
            model_name='acc_details',
            index=models.Index(fields=['created_at'], name='api_acc_det_created_ccc6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['date'], name='api_product_date_ee0cab_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['inward_slip_number'], name='api_product_inward__362d80_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['company_name'], name='api_product_company_7910bb_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['customer_name'], name='api_product_custome_09a8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['programer_status'], name='api_product_program_02630d_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['qa_status'], name='api_product_qa_stat_762c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['outward_status'], name='api_product_outward_45a69c_idx'),
        ),
        migrations.AddIndex(
            model_name='product_details',
            index=models.Index(fields=['created_at'], name='api_product_created_f60610_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['product'], name='api_product_product_586457_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['mat_type'], name='api_product_mat_typ_efc6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['mat_grade'], name='api_product_mat_gra_95ad1e_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['uid_no'], name='api_product_uid_no_d0d861_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['heat_no'], name='api_product_heat_no_8f7c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['programer_status'], name='api_product_program_4c4d38_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['qa_status'], name='api_product_qa_stat_d3420d_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['acc_status'], name='api_product_acc_sta_e890b2_idx'),
        ),
        migrations.AddIndex(
            model_name='product_material',
            index=models.Index(fields=['created_at'], name='api_product_created_b3fb22_idx'),
        ),
        migrations.AddIndex(
            model_name='programer_details',
            index=models.Index(fields=['material'], name='api_program_materia_8a7b10_idx'),
        ),
        migrations.AddIndex(
            model_name='programer_details',
            index=models.Index(fields=['program_no'], name='api_program_program_5cf299_idx'),
        ),
        migrations.AddIndex(
            model_name='programer_details',
            index=models.Index(fields=['program_date'], name='api_program_program_32e386_idx'),
        ),
        migrations.AddIndex(
            model_name='programer_details',
            index=models.Index(fields=['created_at'], name='api_program_created_1daab1_idx'),
        ),
        migrations.AddIndex(
            model_name='qa_details',
            index=models.Index(fields=['material'], name='api_qa_deta_materia_32d50f_idx'),
        ),
        migrations.AddIndex(
            model_name='qa_details',
            index=models.Index(fields=['processed_date'], name='api_qa_deta_process_8189a0_idx'),
        ),
        migrations.AddIndex(
            model_name='qa_details',
            index=models.Index(fields=['created_at'], name='api_qa_deta_created_03fdc5_idx'),
        ),
        migrations.AddIndex(
            model_name='qa_machine_details',
            index=models.Index(fields=['qa'], name='api_qa_mach_qa_id_1d324a_idx'),
        ),
        migrations.AddIndex(
            model_name='qa_machine_details',
            index=models.Index(fields=['machine_name'], name='api_qa_mach_machine_c1d505_idx'),
        ),
        migrations.AddIndex(
            model_name='qa_machine_details',
            index=models.Index(fields=['date'], name='api_qa_mach_date_211746_idx'),
        ),
    ]
