# Generated by Django 5.2.7 on 2026-09-23 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_quotation_quotation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='action',
            field=models.CharField(default='COMPLETED', max_length=50),
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='action_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='performed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machinemaintenancelog',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
