# Generated by Django 5.2.7 on 2026-09-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_machinemaintenancelog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemaintenancelog',
            name='supervised_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='supervised_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
