# Generated by Django 5.2.7 on 2026-09-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_machinemaintenancelog_supervised_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='remind_before_days',
            field=models.IntegerField(default=3, help_text='Days before due date to start reminding'),
        ),
    ]
