# Generated by Django 5.2.7 on 2026-09-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_breakdownmaintenance_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdownmaintenance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='breakdownmaintenancelog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='machinemaintenancelog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='breakdownmaintenance',
            index=models.Index(fields=['breakdown_date'], name='api_breakdo_breakdo_5c3dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmaintenance',
            index=models.Index(fields=['-created_at'], name='api_breakdo_created_e0596e_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmaintenance',
            index=models.Index(fields=['machine', '-created_at'], name='api_breakdo_machine_add691_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmaintenancelog',
            index=models.Index(fields=['action'], name='api_breakdo_action_444550_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmaintenancelog',
            index=models.Index(fields=['-created_at'], name='api_breakdo_created_7f2a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownmaintenancelog',
            index=models.Index(fields=['machine', '-created_at'], name='api_breakdo_machine_2b0b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='machinemaintenancelog',
            index=models.Index(fields=['action'], name='api_machine_action_ffa715_idx'),
        ),
        migrations.AddIndex(
            model_name='machinemaintenancelog',
            index=models.Index(fields=['-created_at'], name='api_machine_created_5b8833_idx'),
        ),
        migrations.AddIndex(
            model_name='machinemaintenancelog',
            index=models.Index(fields=['machine', '-created_at'], name='api_machine_machine_e27f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['next_maintenance_date'], name='api_mainten_next_ma_fc2ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['status'], name='api_mainten_status_feb450_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['machine', 'status'], name='api_mainten_machine_371480_idx'),
        ),
    ]
