# Generated by Django 5.2.7 on 2026-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_breakdownmaintenance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='inventorypart',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='inventorypart',
            index=models.Index(fields=['batch_number'], name='api_invento_batch_n_38b19e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['batch_number'], name='api_invento_batch_n_529907_idx'),
        ),
    ]
