# Generated by Django 5.2.7 on 2026-09-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_inventoryhistory_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypart',
            name='bought_by',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='inventorypart',
            name='warranty',
        ),
    ]
