# Generated by Django 5.2.7 on 2026-09-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_inventorypart_bought_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryusage',
            name='maintenance_type',
        ),
    ]
