# Generated by Django 5.2.7 on 2026-09-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_inventoryusage_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryusage',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_history', to='api.inventorypart'),
        ),
    ]
